# Generated by Django 3.1.7 on 2021-02-22 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openhumans', '0002_openhumansmember_oh_deauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarminMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=255, null=True, unique=True)),
                ('access_token', models.CharField(max_length=512)),
                ('access_token_secret', models.CharField(max_length=512, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('earliest_available_data', models.DateTimeField(null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='garmin_member', to='openhumans.openhumansmember')),
            ],
        ),
    ]
