# Generated by Django 3.1.7 on 2021-02-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garminmember',
            name='earliest_available_data',
        ),
    ]
