# Generated by Django 3.1.7 on 2021-02-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_garminmember_earliest_available_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='garminmember',
            name='has_health_export_permission',
            field=models.BooleanField(default=False),
        ),
    ]
