# Generated by Django 3.2 on 2021-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210420_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garminmember',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='retrieveddata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='summariestoprocess',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
